apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: valkey-es
spec:
  refreshInterval: "0"          
  target:
    name: valkey-secret-test        
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        password: "{{ .password }}"
        username: "default"                
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: valkey-password