apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - valkey-ca-issuer.yaml
  - valkey-server-certificate.yaml
  - valkey-standalone.yaml
  - external-secret.yaml
  - password.yaml