# Server Certificate for Valkey
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: valkey-tls
spec:
  secretTemplate:
    annotations:
      cert-utils-operator.redhat-cop.io/generate-cert-info: "true"
  secretName: valkey-tls-secret
  duration: 8760h  # 365 days
  renewBefore: 720h  # 30 days
  commonName: valkey.nanogw.svc.cluster.local
  usages:
    - digital signature
    - key encipherment
  dnsNames:
    - valkey.nanogw.svc.cluster.local
    - valkey.nanogw.svc
    - valkey-headless.nanogw.svc.cluster.local
    - valkey-headless.nanogw.svc
    - valkey-headless
    - valkey
    - valkey-leader-headless.nanogw.svc.cluster.local
    - valkey-leader-headless.nanogw.svc
    - valkey-leader-headless
    - valkey-leader.nanogw.svc.cluster.local
    - valkey-leader.nanogw.svc
    - valkey-leader
  privateKey:
    algorithm: RSA
    size: 2048
  issuerRef:
    name: valkey-issuer
    kind: Issuer